"""
Integration test demonstrating real-world Quill.js HTML to Typst conversion.

This test showcases a complete document workflow.
"""

import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from html2typst import translate_html_to_typst


def test_real_world_quill_document():
    """Test a realistic Quill.js generated document."""
    
    # This is an example of actual HTML that might be generated by Quill.js
    quill_html = """
    <h1>Technical Report: Q4 2025</h1>
    
    <p class="ql-align-center"><em>Prepared by the Engineering Team</em></p>
    <p class="ql-align-center"><em>January 2026</em></p>
    
    <h2>Executive Summary</h2>
    <p>This quarter has seen <strong>significant progress</strong> across all major initiatives. Key highlights include:</p>
    
    <ul>
        <li>Completed migration to new infrastructure</li>
        <li class="ql-indent-1">Reduced latency by <span style="color: green;">35%</span></li>
        <li class="ql-indent-1">Improved reliability to <span style="color: green;">99.95%</span> uptime</li>
        <li>Launched three new features</li>
        <li class="ql-indent-1">Feature A: User dashboard redesign</li>
        <li class="ql-indent-1">Feature B: Advanced analytics</li>
        <li class="ql-indent-1">Feature C: API v2</li>
    </ul>
    
    <h2>Technical Details</h2>
    <p>The team implemented the following architecture changes:</p>
    
    <pre><code>// New service initialization
const service = new Service({
    timeout: 5000,
    retries: 3,
    cache: true
});</code></pre>
    
    <h3>Performance Metrics</h3>
    <p>Performance improvements were measured across multiple dimensions:</p>
    
    <ol>
        <li>Response time: <strong>-35%</strong></li>
        <li>Memory usage: <strong>-20%</strong></li>
        <li>CPU utilization: <strong>-15%</strong></li>
    </ol>
    
    <h2>Challenges</h2>
    <blockquote>The migration was not without challenges. We encountered several edge cases that required careful handling and testing.</blockquote>
    
    <p>Key challenges included:</p>
    <ul>
        <li>Database migration complexity</li>
        <li>Backward compatibility requirements</li>
        <li>Performance regression testing</li>
    </ul>
    
    <h2>Next Steps</h2>
    <p>Looking forward to Q1 2026, our priorities are:</p>
    
    <ol>
        <li>Scale infrastructure to handle <span style="color: blue;">2x traffic</span></li>
        <li>Implement monitoring improvements</li>
        <li class="ql-indent-1">Add detailed metrics dashboard</li>
        <li class="ql-indent-1">Set up automated alerting</li>
        <li>Continue API development</li>
    </ol>
    
    <h2>Conclusion</h2>
    <p class="ql-align-center">For questions, please contact the team at <a href="mailto:team@example.com">team@example.com</a></p>
    """
    
    # Convert to Typst
    print("Converting Quill.js HTML to Typst...")
    print("="*70)
    
    typst_output = translate_html_to_typst(quill_html, debug=False)
    
    print("\nTypst Output:")
    print("="*70)
    print(typst_output)
    print("="*70)
    
    # Verify key elements are present
    assert "Technical Report: Q4 2025" in typst_output
    assert "= Technical Report: Q4 2025" in typst_output  # H1 formatting
    assert "== Executive Summary" in typst_output  # H2 formatting
    assert "=== Performance Metrics" in typst_output  # H3 formatting
    assert "*significant progress*" in typst_output  # Bold
    assert "_Prepared by the Engineering Team_" in typst_output  # Italic
    assert "#align(center)" in typst_output  # Centered text
    assert "  - Reduced latency" in typst_output or "Reduced latency" in typst_output  # Indented list
    assert "+ Response time" in typst_output  # Ordered list
    assert "- Database migration complexity" in typst_output  # Unordered list
    assert "```" in typst_output  # Code block
    assert "> The migration was not without challenges" in typst_output  # Blockquote
    assert "#link" in typst_output or "team@example.com" in typst_output  # Link
    assert "#text(fill: green)" in typst_output or "35%" in typst_output  # Colored text
    
    print("\n✓ Integration test passed!")
    print("✓ All text preserved")
    print("✓ Structure correctly converted")
    print("✓ Quill.js classes handled properly")
    
    # Also test with debug mode
    print("\n" + "="*70)
    print("Testing debug mode...")
    typst_debug = translate_html_to_typst(quill_html, debug=True)
    
    # In debug mode, text should still be preserved
    assert "Technical Report: Q4 2025" in typst_debug
    assert "significant progress" in typst_debug
    
    print("✓ Debug mode test passed!")
    
    return True


if __name__ == "__main__":
    try:
        test_real_world_quill_document()
        print("\n🎉 All integration tests passed successfully!")
        sys.exit(0)
    except AssertionError as e:
        print(f"\n❌ Integration test failed: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error during integration test: {e}")
        sys.exit(1)
